---
    name: "PR workflow"

    on:
      pull_request:
        types:
          - opened
          - synchronize
          - reopened
          - ready_for_review
        paths-ignore:
          - 'static/**'
          - '**.md'
          - '.gitignore'
          - '.github/ISSUE_TEMPLATE/**'
      workflow_dispatch:
        inputs:
          logLevel:
            description: 'Log level'
            required: true
            default: 'warning'

    env:
      DANDANAPI_APPID: ${{ secrets.DANDANAPI_APPID }}
      DANDANAPI_KEY: ${{ secrets.DANDANAPI_KEY }}
      KAZUMI_APPID: ${{ secrets.KAZUMI_APPID }}
      KAZUMI_KEY: ${{ secrets.KAZUMI_KEY }}

    jobs:
      flutter-test:
        if: ${{ github.event_name == 'workflow_dispatch' || ! github.event.pull_request.draft }}
        runs-on: "ubuntu-latest"
        permissions:
          contents: read
        steps:
          - name: Clone repository
            uses: actions/checkout@v4
          - name: Set up Flutter
            uses: subosito/flutter-action@v2.16.0
            with:
              channel: stable
              flutter-version-file: pubspec.yaml
          - name: Get Flutter dependencies
            run: flutter pub get
            shell: bash
          - name: Run Flutter tests
            run: flutter test
            shell: bash

      flutter-analyze:
        if: ${{ github.event_name == 'workflow_dispatch' || ! github.event.pull_request.draft }}
        runs-on: "ubuntu-latest"
        permissions:
          contents: read
        steps:
          - name: Clone repository
            uses: actions/checkout@v4
          - name: Set up Flutter
            uses: subosito/flutter-action@v2.16.0
            with:
              channel: stable
              flutter-version-file: pubspec.yaml
          - name: Get Flutter dependencies
            run: flutter pub get
            shell: bash
          - name: Analyze Flutter project
            run: flutter analyze --no-fatal-infos --fatal-warnings
            shell: bash

      flutter-build-ios:
        needs: [flutter-test, flutter-analyze]
        if: ${{ github.event_name == 'workflow_dispatch' || ! github.event.pull_request.draft }}
        name: "Build iOS ipa"
        runs-on: "macos-26"
        permissions:
          contents: read
        steps:
          - name: Clone repository
            uses: actions/checkout@v4
          - name: Set up Flutter
            uses: subosito/flutter-action@v2.16.0
            with:
              channel: stable
              flutter-version-file: pubspec.yaml
          - name: Get Flutter dependencies
            run: flutter pub get
          - name: Build IPA
            run: >-
              flutter build ios --release --no-codesign
              --dart-define=DANDANAPI_APPID=$DANDANAPI_APPID
              --dart-define=DANDANAPI_KEY=$DANDANAPI_KEY
              --dart-define=KAZUMI_APPID=$KAZUMI_APPID
              --dart-define=KAZUMI_KEY=$KAZUMI_KEY
          - name: Create IPA
            run: |
              mkdir Payload
              cp -R build/ios/iphoneos/Runner.app Payload/Runner.app
              find Payload/Runner.app/Frameworks -type d -name "*.framework" -exec codesign --force --sign - --preserve-metadata=identifier,entitlements {} \;
              zip -q -r Kazumi_ios_canary_no_sign.ipa Payload
          - name: Upload iOS build
            uses: actions/upload-artifact@v4
            with:
              name: ios_outputs
              path: Kazumi_ios_*.ipa
