---
    name: "release"

    on:
      push:
        tags:
          - "*"
      workflow_dispatch:
        inputs:
          logLevel:
            description: 'Log level'
            required: true
            default: 'warning'

    env:
      DANDANAPI_APPID: ${{ secrets.DANDANAPI_APPID }}
      DANDANAPI_KEY: ${{ secrets.DANDANAPI_KEY }}
      KAZUMI_APPID: ${{ secrets.KAZUMI_APPID }}
      KAZUMI_KEY: ${{ secrets.KAZUMI_KEY }}

    jobs:
      flutter-test:
        runs-on: "ubuntu-latest"
        permissions:
          contents: read
        steps:
          - name: Clone repository
            uses: actions/checkout@v4
          - name: Set up Flutter
            uses: subosito/flutter-action@v2.16.0
            with:
              channel: stable
              flutter-version-file: pubspec.yaml
          - name: Get Flutter dependencies
            run: flutter pub get
            shell: bash
          - name: Run Flutter tests
            run: flutter test
            shell: bash

      flutter-analyze:
        runs-on: "ubuntu-latest"
        permissions:
          contents: read
        steps:
          - name: Clone repository
            uses: actions/checkout@v4
          - name: Set up Flutter
            uses: subosito/flutter-action@v2.16.0
            with:
              channel: stable
              flutter-version-file: pubspec.yaml
          - name: Get Flutter dependencies
            run: flutter pub get
            shell: bash
          - name: Analyze Flutter project
            run: flutter analyze --no-fatal-infos --fatal-warnings
            shell: bash

      flutter-build-ios:
        name: "Release for iOS"
        needs: [flutter-test, flutter-analyze]
        runs-on: "macos-26"
        permissions: write-all

        steps:
          - name: Clone repository
            uses: actions/checkout@v4
          - name: Extract tag name
            run: echo "tag=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV
          - name: Echo build progress
            run: echo "Kazumi_ios_${{ env.tag }}.ipa build progress"
          - name: Set up Flutter
            uses: subosito/flutter-action@v2.16.0
            with:
              channel: stable
              flutter-version-file: pubspec.yaml
          - run: flutter pub get
          - name: Build IPA
            run: >-
              flutter build ios --release --no-codesign
              --dart-define=DANDANAPI_APPID=$DANDANAPI_APPID
              --dart-define=DANDANAPI_KEY=$DANDANAPI_KEY
              --dart-define=KAZUMI_APPID=$KAZUMI_APPID
              --dart-define=KAZUMI_KEY=$KAZUMI_KEY
          - name: Create IPA
            run: |
              mkdir Payload
              cp -R build/ios/iphoneos/Runner.app Payload/Runner.app
              find Payload/Runner.app/Frameworks -type d -name "*.framework" -exec codesign --force --sign - --preserve-metadata=identifier,entitlements {} \;
              zip -q -r Kazumi_ios_${{ env.tag }}_no_sign.ipa Payload
          - name: Upload iOS build
            uses: actions/upload-artifact@v4
            with:
              name: ios_outputs
              path: Kazumi_ios_*.ipa

      release:
        name: "Release"
        runs-on: "ubuntu-latest"
        needs: [flutter-build-ios]
        permissions: write-all
        steps:
          - name: Clone repository
            uses: actions/checkout@v4
          - name: Extract tag name
            run: echo "tag=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV
            shell: bash
          - name: Download iOS build file
            uses: actions/download-artifact@v4
            with:
              name: ios_outputs
              path: ios_outputs
          - name: List files in ios_outputs directory
            run: ls -l ios_outputs
          - name: Copy ios build file to root
            run: cp ios_outputs/* Kazumi_ios_${{ env.tag }}_no_sign.ipa
          - name: Create release
            uses: softprops/action-gh-release@v2
            with:
              files: |
                Kazumi_ios_*.ipa
